# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db176d5160b596d87c6b72f27ef594563745aba0e11d771463d1603cff99ea65062d0d8c7493c254766ef1a37f9628a1b44b733d1d4cf2abca0eda555f228745

test:
  secret_key_base: 20021ea8cb69405eae2e29f92e48a695aa47c668fe474fbe68f4edf2a953e79ce7b43fa1ed1a53f42f01b195a07115bd9cc27084aac18225bf52bc18520d365c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
